-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE,       -- G, PG, PG-13, R, NC-17
    description VARCHAR(255)                -- Описание возрастного ограничения
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE         -- Комедия, Драма, Триллер и т.д.
);

-- Таблица статусов дружбы
CREATE TABLE IF NOT EXISTS friendship_statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE         -- 'UNCONFIRMED', 'CONFIRMED'
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    mpa_rating_id INTEGER REFERENCES mpa_ratings(id) ON DELETE RESTRICT
);

-- Жанры фильма
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

-- Лайки фильмов
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Дружба между пользователями со статусом
CREATE TABLE IF NOT EXISTS user_friends (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,       -- Кто отправил запрос
    friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,     -- Кому отправили
    status_id INTEGER REFERENCES friendship_statuses(id) ON DELETE RESTRICT,
    PRIMARY KEY (user_id, friend_id),
    CHECK (user_id <> friend_id)
);
